name: Deploy Client

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repoistory
        uses: actions/checkout@v2
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install NX
        run: npm install -g nx
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: nx run caretaker-client:build
      - name: Deploy to S3
        run: aws s3 sync dist/apps/caretaker-client s3://${{ secrets.AWS_CARETAKER_CLIENT_BUCKET_NAME }} --recursive
      - name: Create Cloudfront Invalidation
        run: aws cloudfront create-invalidation --distribution ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

